version: "3.8"

services:
  bot:
    build: .
    container_name: bot_app
    depends_on:
      - db
    environment:
      - BOT_TOKEN=8730907685:AAHYobmvtFepUP_Vum05Y8dkVulF-Sw8eRg
    command: python main.py

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: